# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobilecenter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobilecenter
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

  

  target 'mobilecenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mobilecenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobilecenter-tvOS

  target 'mobilecenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
